{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules: 
{{ toYaml .Values.ingress.rules | nindent 6 }}
  {{- if .Values.ingress.tlsEnable }}
  tls: 
{{ toYaml .Values.ingress.tls | nindent 6 }}
  {{- end }}
{{- end }}