apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  image: rabbitmq:3.12-management
  rabbitmq:
    additionalPlugins:
      - rabbitmq_prometheus
      - rabbitmq_stream
    additionalConfig: |
      {{- if .Values.rabbitmqConf.default_user }}
      default_user = {{ .Values.rabbitmqConf.default_user }}
      {{- end }}
      {{- if .Values.rabbitmqConf.default_pass }}
      default_pass = {{ .Values.rabbitmqConf.default_pass }}
      {{- end }}
      {{- if .Values.rabbitmqConf.default_user_tags.administrator }}
      default_user_tags.administrator = {{ .Values.rabbitmqConf.default_user_tags.administrator }}
      {{- end }}
      {{- if .Values.rabbitmqConf.log.console.level }}
      log.console.level = {{ .Values.rabbitmqConf.log.console.level }}
      {{- end }}