apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "rabbitmq.selectorLabels" . | nindent 6 }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  resources:
    {{- toYaml .Values.resources | nindent 4 }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  {{- if .Values.image.pullPolicy }}
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  {{- end }}
  ports: 
    {{- toYaml .Values.container.ports | nindent 4}}
  rabbitmq:
    {{- if .Values.additionalPlugins }}
    additionalPlugins:
{{ toYaml .Values.additionalPlugins | nindent 8 }}
    {{- end }}
    {{- if .Values.additionalConfig }}
    additionalConfig: |
{{ .Values.additionalConfig | nindent 8}}
    {{- end }}
