rabbitmq:
  fullname: rabbitmq
  labels:
    app: rabbitmq
    name: rabbitmq
  selectorLabels:
    app: rabbitmq
    name: rabbitmq

imagePullSecrets: []    
nameOverride:
fullnameOverride:

autoscaling:
  enabled: false
replicaCount: 1

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 1Gi
  # requests:
  #   cpu: 500m
  #   memory: 1Gi

container:
  ports:
    - name: management
      containerPort: 15672
      protocol: TCP
    - name: monitoring
      containerPort: 15692
      protocol: TCP
    - name: amqp
      containerPort: 5672
      protocol: TCP

image:
  repository: rabbitmq
  tag: 3.12-management
  pullPolicy: IfNotPresent
additionalPlugins:
  - rabbitmq_prometheus
  - rabbitmq_stream
additionalConfig: |
      default_user = samuel
      default_pass = samuel
      default_user_tags.administrator = true
      log.console.level = info
      consumer_timeout = 3600000
      vm_memory_high_watermark.relative = 0.8

ingress:
  enabled: true
  className: nginx
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true" 
  rules:
    - host: rabbitm.queue.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: rabbitmq
                port:
                  number: 5672
    - host: rabbitm.qui.com
      http:
        paths:
          - backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
            path: "/"
            pathType: ImplementationSpecific
    - host: rabbitm.qmetrics.com
      http:
        paths:
          - backend:
              service:
                name: rabbitmq
                port:
                  number: 15692
            path: /metrics
            pathType: Prefix
  tlsEnable: false
  tls:
    - hosts:
        - rabbitm.qui.com
      secretName: example-tls