rabbitmqConf:
  listeners:
    tcp:
      tcp:
      default: 5672
      local:
      local_v6:
      other_port: 15672
    ssl:
      default:
  num_acceptors:
    tcp:
    ssl:
  socket_writer:
    gc_threshold:
  handshake_timeout:
  reverse_dns_lookups: true
  loopback_users:
    guest: false
  ssl_options:
    verify:
    fail_if_no_peer_cert:
    cacertfile:
    certfile:
    keyfile:
    honor_cipher_order:
    honor_ecc_order:
    client_renegotiation:
    secure_renegotiate:
    versions1:
    versions2:
    ciphers1:
    ciphers2:
    ciphers3:
    ciphers4:
    ciphers5:
    ciphers6:
    ciphers7:
    ciphers8:
    ciphers9:
    ciphers10:
    ciphers11:
    ciphers12:
    ciphers13:
    ciphers14:
    ciphers15:
    ciphers16:
    ciphers17:
    ciphers18:
    ciphers19:
    ciphers20:
    ciphers21:
    ciphers22:
    ciphers23:
    ciphers24:
    ciphers25:
    ciphers26:
    ciphers27:
    ciphers28:
    ciphers29:
    ciphers30:
    ciphers31:
    ciphers32:
    ciphers33:
    ciphers34:
    ciphers35:
    ciphers36:
    bypass_pem_cache:
  auth_backends1:
    authn:
    authz:
    auth_backends:
  auth_backends2:
  auth_mechanisms1:
  auth_mechanisms2:
  auth_mechanisms3:
  ssl_cert_login_from:
  ssl_handshake_timeout:
  load_definitions:
  cluster_name:
  password_hashing_module:
  default_vhost:
  default_user: samuel
  default_pass: samuel
  default_permissions:
    configure:
    read:
    write:
  default_user_tags:
    administrator: true
    management: 
    custom_tag:
  heartbeat:
  frame_max:
  initial_frame_max:
  channel_max:
  tcp_listen_options:
    backlog:
    nodelay:
    exit_on_close:
    keepalive:
    send_timeout:
    buffer:
    sndbuf:
    recbuf:
  vm_memory_high_watermark:
    relative: 0.8
    absolute:
  vm_memory_high_watermark_paging_ratio:
  vm_memory_calculation_strategy:
  memory_monitor_interval:
  total_memory_available_override_value:
  disk_free_limit:
    absolute:
    relative:
  cluster_partition_handling:
    cluster_partition_handling:
    pause_if_all_down:
      recover:
      nodes1:
      nodes2:
  mirroring_sync_batch_size:
  cluster_formation:
    peer_discovery_backend:
    classic_config:
      nodes1:
      nodes2:
      nodes3:
      nodes4:
    dns:
      hostname:
    node_type:
  cluster_keepalive_interval:
  collect_statistics_interval:
  raft:
    segment_max_entries:
    wal_max_size_bytes:
    wal_max_batch_size:
    snapshot_chunk_size:
  deprecated_features:
    permit:
      a_deprecated_feature:
      another_deprecated_feature:
  mnesia_table_loading_retry_timeout:
  mnesia_table_loading_retry_limit:
  queue_index_embed_msgs_below:
  background_gc_enabled:
  background_gc_target_interval:
  proxy_protocol:
  product:
    name:
    version:
  motd_file:
  consumer_timeout:
  net_ticktime:
  management:
    load_definitions:
    http_log_dir:
    tcp:
      port:
      ip:
      shutdown_timeout:
      max_keepalive:
      idle_timeout:
      inactivity_timeout:
      request_timeout:
      compress:
    ssl:
      port:
      cacertfile:
      certfile:
      keyfile:
      honor_cipher_order:
      honor_ecc_order:
      client_renegotiation:
      secure_renegotiate:
      versions1:
      ciphers1:
      ciphers2:
      ciphers3:
      ciphers4:
      ciphers5:
      ciphers6:
      ciphers7:
      ciphers8:
      ciphers9:
      ciphers10:
    path_prefix:
    rates_mode:
    sample_retention_policies:
      global:
        minute:
        hour:
        day:
      basic:
        minute:
        hour:
        detailed10:
  stomp:
    listeners:
      tcp1:
      tcp2:
      ssl:
        default:
    tcp_listen_options:
      backlog:
      recbuf:
      sndbuf:
      keepalive:
      nodelay:
      exit_on_close:
      send_timeout:
    proxy_protocol:
    num_acceptors:
      tcp:
      ssl:
    ssl_cert_login:
    default_user:
    default_pass:
    implicit_connect:
  mqtt:
    listeners:
      tcp1:
      tcp2:
      ssl:
        default:
    tcp_listen_options:
      backlog:
      recbuf:
      sndbuf:
      keepalive:
      nodelay:
      exit_on_close:
      send_timeout:
    num_acceptors:
      tcp:
      ssl:
    proxy_protocol:
    default_user:
    default_pass:
    allow_anonymous:
    vhost:
    exchange:
    max_session_expiry_interval_secs:
    prefetch:
    durable_queue_type:
  amqp1_0:
    default_user:
    protocol_strict_mode:
  log:
    dir:
    file:
      file:
      level:
      rotation:
        date:
        size:
    console:
      console: true
      level: info
    exchange:
      exchange:
      level:
  auth_ldap:
    servers1:
    servers2:
    use_ssl:
    port:
    timeout:
    log:
    user_dn_pattern:
    dn_lookup_attribute:
    dn_lookup_base:
    other_bind:
      other_bind:
      user_dn:
      password:

